#!/bin/bash
echo "Running post-process build scripts."
for script in `/bin/ls -1 ./PostProcessRuby | grep .rb$`; do
    echo "%%%%%% Start $script %%%%%%"
    "ruby ./PostProcessRuby/$script" "$@"
    echo "%%%%%%  End  $script %%%%%%"
done
